### ISSUE TITLE
when i use 2.5.2 App crash,use 2.5.1 is ok

### ISSUE THREAD

**Issue by StevenHX** [alexvasilkov/GestureViews#139]
019-04-11 10:04:52.590 25310-25310/com.dealy1688.android.shop E/JC-CrashHandler: │ Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alexvasilkov/gestures/R$styleable;
2019-04-11 10:04:52.590 25310-25310/com.dealy1688.android.shop E/JC-CrashHandler: │ 	at com.alexvasilkov.gestures.Settings.initFromAttributes(Settings.java:153)
2019-04-11 10:04:52.590 25310-25310/com.dealy1688.android.shop E/JC-CrashHandler: │ 	at com.alexvasilkov.gestures.views.GestureImageView.<init>(GestureImageView.java:61)
2019-04-11 10:04:52.590 25310-25310/com.dealy1688.android.shop E/JC-CrashHandler: │ 	at com.alexvasilkov.gestures.views.GestureImageView.<init>(GestureImageView.java:54)
2019-04-11 10:04:52.590 25310-25310/com.dealy1688.android.shop E/JC-CrashHandler: │ 	... 58 more
2019-04-11 10:04:52.590 25310-25310/com.dealy1688.android.shop E/JC-CrashHandler: │ Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alexvasilkov.gestures.R$styleable"

**Comment by alexvasilkov** [comment]
Hm, looks like a build issue on your side, please try a clean build. We are using v2.5.2 in several production applications for a long time now and never had such issue.
