### ISSUE TITLE
NullPointerException when using touch without ViewPager

### ISSUE THREAD

**Issue by strombringer** [alexvasilkov/GestureViews#15]
I'm trying out your library in version 2.1.0 and created a minimal (I think) example for it:

Activity:
```Java
public class TestActivity extends AppCompatActivity {

	private GestureImageView gestureView;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_test);

		gestureView = (GestureImageView) findViewById(R.id.imageView);

		String assetPath = "file:///android_asset/my_image.png";
		Glide.with(this)
			.load(assetPath)
			.into(gestureView);
	}
}
```

Layout:
```Xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

	<com.alexvasilkov.gestures.views.GestureImageView
		android:id="@+id/imageView"
		android:layout_width="match_parent"
		android:layout_height="match_parent"/>

</LinearLayout>
```

When I touch the image in the emulator or on my phone, the app crashes with this exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.requestDisallowInterceptTouchEvent(boolean)' on a null object reference
   at com.alexvasilkov.gestures.GestureControllerForPager.onDown(GestureControllerForPager.java:128)
   at com.alexvasilkov.gestures.GestureController$InternalGesturesListener.onDown(GestureController.java:745)
   at android.view.GestureDetector.onTouchEvent(GestureDetector.java:590)
   at com.alexvasilkov.gestures.GestureController.onTouch(GestureController.java:340)
   at com.alexvasilkov.gestures.GestureControllerForPager.onTouch(GestureControllerForPager.java:100)
   at com.alexvasilkov.gestures.views.GestureImageView.onTouchEvent(GestureImageView.java:140)
   at android.view.View.dispatchTouchEvent(View.java:9294)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
```

Am I using the library correctly?

**Comment by alexvasilkov** [comment]
Yeah, sorry about that, version 2.1.1 which fixes this bug is on it's way to Maven Central.

**Comment by strombringer** [comment]
Great, thank you! :+1:
