### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to draw too large(272432496bytes) bitmap.

### ISSUE THREAD

**Issue by idineshgovind** [alexvasilkov/GestureViews#186]
java.lang.RuntimeException: Canvas: trying to draw too large(272432496bytes) bitmap.
    at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:301)
    at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:196)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
    at android.widget.ImageView.onDraw(ImageView.java:1449)
    at android.view.View.draw(View.java:23568)
    at com.alexvasilkov.gestures.views.GestureImageView.draw(GestureImageView.java:88)
    
    
    any fix for this issue? 
     at com.alexvasilkov.gestures.views.GestureImageView.draw(GestureImageView.java:88)

**Comment by alexvasilkov** [comment]
Duplicate. Check #180 or other similar issues.

**Comment by idineshgovind** [comment]
issue was fixed when i add 
.downsample(DownsampleStrategy.AT_MOST) 
to my glide and I confirm this issue is not from this library and it is from Glide
