### ISSUE TITLE
I had this error after double tap to the gestureImageView

### ISSUE THREAD

**Issue by developer--** [alexvasilkov/GestureViews#45]
**# This happen's randomly, the problem acquires after double tapping than press the back button and again click the imageview and touch the gestureimageview**  

`09-07 13:20:26.499 14100-14100/com.leavingstone.aversi E/InputEventReceiver: Exception dispatching input event.
09-07 13:20:26.499 14100-14100/com.leavingstone.aversi E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-07 13:20:26.509 14100-14100/com.leavingstone.aversi E/MessageQueue-JNI: java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:406)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:408)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:408)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:408)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:408)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:408)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformMatrixToPager(GestureControllerForPager.java:408)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.transformToPagerEvent(GestureControllerForPager.java:391)
                                                                               at com.alexvasilkov.gestures.GestureControllerForPager.onTouch(GestureControllerForPager.java:104)
                                                                               at com.alexvasilkov.gestures.views.GestureImageView.onTouchEvent(GestureImageView.java:140)
                                                                               at android.view.View.dispatchTouchEvent(View.java:7723)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2117)
                                                                               at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1564)
                                                                               at android.app.Dialog.dispatchTouchEvent(Dialog.java:797)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2065)
                                                                               at android.view.View.dispatchPointerEvent(View.java:7903)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4174)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4053)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3610)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3660)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3629)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3736)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3637)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3793)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3610)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3660)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3629)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3637)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3610)
                                                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5822)
                                                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5802)
                                                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5773)
                                                                               at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5911)
                                                                               at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                            at android.os.MessageQueue.next(MessageQueue.j`

**Comment by alexvasilkov** [comment]
Can't reproduce it, maybe it's somehow related to Glide? I experienced some strange behavior with its default animations. Setting custom animation helped to solved it.
Anyway, I fixed the code, so it should not crash, but I can't guarantee correct visual behavior. So please test it again, and reopen ticket if you'll see something bad.
